MySite/Models/EmailService.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MimeKit;
using MailKit.Net.Smtp;

namespace SocialApp.Services {
    public class EmailService {
        public async Task SendEmailAsync(string name, string email, string phone, string message) {
            var emailMessage = new MimeMessage();

            emailMessage.From.Add(new MailboxAddress("Администрация сайта", "tilda.002@yandex.ru"));
            emailMessage.To.Add(new MailboxAddress("Администрация сайта", "wowa.98@mail.ru"));
            emailMessage.Subject = "Письмо с сайта: от " + name + ", EMail: " + email + ", Phone: " + phone;
            emailMessage.Body = new TextPart("Plain") {
                Text = message
            };

            using (var client = new SmtpClient()) {
				try {
					await client.ConnectAsync("smtp.yandex.ru", 25, false);
					await client.AuthenticateAsync("tilda.002@yandex.ru", "002tilda002");
					await client.SendAsync(emailMessage);

					await client.DisconnectAsync(true);
				}
				catch (Exception ex) {
                    var q = ex.Message;
				}
                
            }
        }
    }
}

MySite/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MySite.Models {
	public class LoginViewModel {
		[Required]
		[Display(Name = "Логин")]
		public string UserName { get; set; }

		[Required]
		[UIHint("Password")]
		[Display(Name = "Пароль")]
		public string Password { get; set; }

		[Display(Name = "Запомнить меня?")]
		public bool RememberMe { get; set; }
	}
}

MySite/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MySite.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MySite.Areas.Admin.Controllers {
	[Area("Admin")]
	public class HomeController : Controller {
		private readonly DataManager dataManager;
		public HomeController(DataManager dataManager) {
			this.dataManager = dataManager;
		}
		public IActionResult Index() {
			return View(dataManager.ServiceItems.GetServiceItems());
		}
	}
}

MySite/Areas/Admin/Controllers/ServiceItemsController.cs
using System;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MySite.Domain;
using MySite.Domain.Entities;
using MySite.Service;

namespace MySite.Areas.Admin.Controllers {
    [Area("Admin")]
    public class ServiceItemsController : Controller {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;
        public ServiceItemsController(DataManager dataManager, IWebHostEnvironment hostingEnvironment) {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Edit(Guid id) {
            var entity = id == default ? new ServiceItem() : dataManager.ServiceItems.GetServiceItemById(id);
            return View(entity);
        }
        [HttpPost]
        public IActionResult Edit(ServiceItem model, IFormFile titleImageFile) {
            if (ModelState.IsValid) {
                if (titleImageFile != null) {
                    model.TitleImagePath = titleImageFile.FileName;
                    using (var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "images/", titleImageFile.FileName), FileMode.Create)) {
                        titleImageFile.CopyTo(stream);
                    }
                }
                dataManager.ServiceItems.SaveServiceItem(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Guid id) {
            dataManager.ServiceItems.DeleteServiceItem(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
    }
}

MySite/Areas/Admin/Controllers/TextFieldsController.cs
using Microsoft.AspNetCore.Mvc;
using MySite.Domain;
using MySite.Domain.Entities;
using MySite.Service;

namespace MySite.Areas.Admin.Controllers {
    [Area("Admin")]
    public class TextFieldsController : Controller {
        private readonly DataManager dataManager;
        public TextFieldsController(DataManager dataManager) {
            this.dataManager = dataManager;
        }

        public IActionResult Edit(string codeWord) {
            var entity = dataManager.TextFields.GetTextFieldByCodeWord(codeWord);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Edit(TextField model) {
            if (ModelState.IsValid) {
                dataManager.TextFields.SaveTextField(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }
    }
}

MySite/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MySite.Models;
using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;

namespace MySite.Controllers {
	[Authorize]
	public class AccountController : Controller {
		private readonly UserManager<IdentityUser> userManager;
		private readonly SignInManager<IdentityUser> signInManager;
		public AccountController(UserManager<IdentityUser> userMng, SignInManager<IdentityUser> singInMng) {
			userManager = userMng;
			signInManager = singInMng;
		}

		[AllowAnonymous]
		public IActionResult Login(string returnUrl) {
			ViewBag.returnUrl = returnUrl;
			return View(new LoginViewModel());
		}

		[HttpPost]
		[AllowAnonymous]
		public async Task<IActionResult> Login(LoginViewModel model, string returnUrl) {
			if (ModelState.IsValid) {
				IdentityUser user = await userManager.FindByNameAsync(model.UserName);
				if (user != null) {
					await signInManager.SignOutAsync();
					Microsoft.AspNetCore.Identity.SignInResult result = await signInManager.PasswordSignInAsync(user, model.Password, model.RememberMe, false);
					if (result.Succeeded) {
						return Redirect(returnUrl ?? "/");
					}
				}
				ModelState.AddModelError(nameof(LoginViewModel.UserName), "Неверный логин или пароль");
			}
			return View(model);
		}

		[Authorize]
		public async Task<IActionResult> Logout() {
			await signInManager.SignOutAsync();
			return RedirectToAction("Index", "Home");
		}
	}
}

MySite/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MySite.Domain;
using MySite.Models;
using SocialApp.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MySite.Controllers {
	public class HomeController : Controller {
		private readonly DataManager dataManager;

		public HomeController(DataManager dataManager) {
			this.dataManager = dataManager;
		}
		public IActionResult Index() {
			return View(dataManager.ServiceItems.GetServiceItems());
		}

		[HttpPost]
		public async Task<IActionResult> SendMessage(string name, string email, string phone, string message) {
			EmailService emailService = new EmailService();
			await emailService.SendEmailAsync(name, email, phone, message);
			return Redirect("/");
		}
	}
}

MySite/Areas/Admin/Views/Home/Index.cshtml
@model IQueryable<ServiceItem>
@{ 
    string strTitle = "Панель администратора";
    ViewBag.Title = strTitle;
}

<div>
	<h1>@strTitle</h1>
    <div>
        <h3>Наши услуги</h3>
        <div class="div-box">
            <a asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" asp-route-id="">Добавить услугу</a>
        </div>
        @if (Model.Any()) {
            <div>
                @foreach (ServiceItem entity in Model) {
                <div>
                    <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="@entity.Id">
                        @($"{entity.Title}")
                    </a>
                    <a> | </a>
                    <a asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" asp-route-id="@entity.Id">редактировать</a>
                    <a> | </a>
                    <form style="display: inline-block;" id="form-@entity.Id" asp-area="Admin" asp-controller="ServiceItems" asp-action="Delete" method="post">
                        <input type="hidden" name="id" value="@entity.Id" />
                        <a href="#" onclick="document.getElementById('form-@entity.Id').submit();">удалить</a>
                    </form>
                </div>
                }
            </div>
        }
    </div>
	<div class="div-box">
		<h3>Редактировать страницы сайта</h3>
		<a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageIndex">Главная</a>
		<a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageServices">Мои услуги</a>
		<a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageContacts">Контакты</a>
	</div>
	<div class="div-box">
		<form asp-area="" asp-controller="Account" asp-action="Logout" method="post">
			<input type="submit" value="Выйти" />
		</form>
	</div>
</div>

MySite/Areas/Admin/Views/ServiceItems/Edit.cshtml
@model ServiceItem
@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}

<script src="~/js/ckeditor/ckeditor.js"></script>

<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />
            <input type="hidden" asp-for="TitleImagePath" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="Subtitle"></label>
                <input asp-for="Subtitle" />
                <span asp-validation-for="Subtitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="TitleImagePath"></label>
                <input type="file" name="titleImageFile" id="titleImageFile" />
                <div>
                    <img class="img-block" src="~/images/@Model.TitleImagePath" />
                </div>
            </div>
            <div class="div-box">
                <label asp-for="MetaTitle"></label>
                <input asp-for="MetaTitle" />
                <span asp-validation-for="MetaTitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaDescription"></label>
                <input asp-for="MetaDescription" />
                <span asp-validation-for="MetaDescription"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaKeywords"></label>
                <input asp-for="MetaKeywords" />
                <span asp-validation-for="MetaKeywords"></span>
            </div>
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>



<script>
    window.onload = function() {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x => x.Text)');
        newCKEdit.updateElement();
    }
</script>

MySite/Areas/Admin/Views/TextFields/Edit.cshtml
@model TextField
@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}

<script src="~/js/ckeditor/ckeditor.js"></script>

<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-area="Admin" asp-controller="TextFields" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />
            <input type="hidden" asp-for="CodeWord" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaTitle"></label>
                <input asp-for="MetaTitle" />
                <span asp-validation-for="MetaTitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaDescription"></label>
                <input asp-for="MetaDescription" />
                <span asp-validation-for="MetaDescription"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaKeywords"></label>
                <input asp-for="MetaKeywords" />
                <span asp-validation-for="MetaKeywords"></span>
            </div>
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>



<script>
    window.onload = function() {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x=>x.Text)');
        newCKEdit.updateElement();
    }
</script>

MySite/Views/Shared/CssPartial.cshtml
<link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />

MySite/Views/Shared/FooterPartial.cshtml
<footer id="footer">
    <div class="inner">
        <ul class="icons">
            <li><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"><a href="https://vk.com/vladimirvechkanov" target="_blank"><i class="fa fa-vk fa-2x"></i></a></li>
            <li><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"><a href="https://www.instagram.com/vladimirvechkanov.1/" target="_blank"><i class="fa fa-instagram fa-2x"></i></a></li>
            <li><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"><a href="https://github.com/wowa683?tab=repositories" target="_blank"><i class="fa fa-github fa-2x"></i></a></li>
            <li><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"><a class="slow_bottom" href="#bottom"><i class="fa fa-phone-square fa-2x"></i></a></li>
            <li><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"><a href="mailto:wowa.98@mail.ru"><i class="fa fa-envelope fa-2x"></i></a></li>
        </ul>
        <ul class="copyright">
            <li>&copy; Vladimir Vechkanov. All rights reserved.</li>
            <li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
        </ul>
    </div>
</footer>

MySite/Views/Shared/HeaderPartial.cshtml
<header id="header">
    <div class="inner">
        <a href="/" class="image avatar"><img src="~/images/IMG_7914.JPG" alt="" /></a>
        <h1>
            Здравствуйте!<br />
            Меня зовут <strong>Владимир</strong>,<br />
            я <strong>Full-Stack Developer.</strong><br />
            Готов решать сложные задачи.

        </h1>
    </div>
</header>

MySite/Views/Shared/MetatagsPartial.cshtml
@using MySite.Service
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
@if (ViewBag.Title != null) {
    <title>@ViewBag.Title</title>
}
else {
    <title>@Config.MyName</title>
}
@if (ViewBag.Description != null) {
    <meta name="description" content="@ViewBag.Description" />
}
@if (ViewBag.Keywords != null) {
    <meta name="keywords" content="@ViewBag.Keywords" />
}

MySite/Views/Shared/ScriptsPartial.cshtml
<script src="~/js/scripts.min.js" asp-append-version="true"></script>

MySite/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>

<html>
<head>
	@await Html.PartialAsync("MetatagsPartial")
	@await Html.PartialAsync("CssPartial")
</head>
<body class="is-preload">
	@await Html.PartialAsync("HeaderPartial")
	<div id="main">
		@RenderBody()
	</div>
	@await Html.PartialAsync("FooterPartial")
	@await Html.PartialAsync("ScriptsPartial")
</body>
</html>